//Desafio 01/04/2024 - Crie um programa que armazene os seguintes dados: 
//nome do funcionário, salário e cargo e imprima no console os 3 valores;

package application;

public class App {
    static String nomeFuncionario = "Ana da Silva";
    static String cargo = "Supervisor Administrativo";
    static double salario R$ = 6950.80;
    public static void main(String[] args){
        System.out.println("Funcionario:" + nomeFuncionario);
        System.out.println("Cargo: " + cargo);
        System.out.println("Salário R$:" + salario);

    }}
