public class funcionarios1 {

    static String nomeFuncionario = "José da Silva";
    static String cargoFuncionario = "Analista de dados";
    static double salarioTFuncionario =  12500.00;

    public static void main(String[] args) throws Exception {
        System.out.println("Nome do funcionário: " + nomeFuncionario);
        System.out.println("Cargo: " + cargoFuncionario);
        System.out.println("Salário: R$ " + salarioTFuncionario);
    }
}